Plugin trialing
Saul-Mirone/milkdown pull request #537
Opened 2022-05-31 08:17 UTC by 4-1-1

Append an empty paragraph  when  table is the last node

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/4401981/171124619-61c6279a-f91a-4665-91c9-5894b82c3e26.png">

2022-06-17 06:07 UTC, 4-1-1 commented
@Saul-Mirone Do you have time to review it

2022-06-17 06:37 UTC, Saul-Mirone commented
> @Saul-Mirone Do you have time to review it

I've already reviewed it a week ago.

2022-06-17 06:38 UTC, Saul-Mirone reviewed
Added some comments

2022-06-17 06:38 UTC, Saul-Mirone commented on packages/plugin-trailing/package.json
> +    "version": "6.0.1",
Align the version with other packages.

2022-06-17 06:38 UTC, Saul-Mirone commented on packages/plugin-trailing/src/index.ts
> +export const trailingNode: any = createPlugin(() => {
No any

2022-06-17 06:38 UTC, Saul-Mirone commented on packages/plugin-trailing/src/trailing.ts
> +const name = new PluginKey('trailingNode');
Follow others plugin's key name

2022-06-17 06:38 UTC, Saul-Mirone commented on packages/plugin-trailing/src/trailing.ts
> +                    view.dispatch(transaction);
This will add a record in history, consider using `appendTransaction` or set the metadata of `addToHistory` to avoid this.

2022-06-17 06:38 UTC, Saul-Mirone commented on packages/preset-commonmark/src/node/paragraph.ts
> +            if (content === '\\') {
What if user just want to add `\\`?

2022-06-17 06:41 UTC, Saul-Mirone commented on packages/plugin-trailing/package.json
> +    "devDependencies": {
Add proper dependencies and peer dependencies

2022-06-17 06:42 UTC, Saul-Mirone commented on packages/plugin-trailing/src/trailing.ts
> +                    const type = schema.nodes['paragraph'];
We should make the created node type can be configured by users.

2022-06-17 06:43 UTC, Saul-Mirone requested changes
Update comments

2022-06-17 06:44 UTC, Saul-Mirone commented on packages/plugin-trailing/README.md
> +# @milkdown/plugin-trailing
Follow other plugin's readme, we put documents in website now.

2022-06-17 06:46 UTC, Saul-Mirone commented on packages/preset-commonmark/README.md
> +```typescript
Follow other plugin's readme, we put documents in website now.

2022-06-20 02:42 UTC, 4-1-1 commented on packages/preset-commonmark/src/node/paragraph.ts
> +            if (content === '\\') {
I think it is meaningless of '\' in a single line .  Otherwise ,It is up to the config

2022-06-20 02:45 UTC, 4-1-1 commented on packages/plugin-trailing/src/trailing.ts
> +                    view.dispatch(transaction);
Don't know how to use appendTransaction . Just add a metaData `setMeta('addToHistory', false);`

2022-06-20 05:46 UTC, Saul-Mirone commented
I think your PR has two features:

1. Keep empty lines in markdown
2. Add trailing node plugin

I don't plan to make feature 1 part of official plugins because I think it's not part of markdown standard and the implementation is a little bit tricky. It would be better to make it as a community plugin.

The feature 2 is a good feature but I think you should make it as a standalone plugin rather than part of commonmark preset.

BTW, the branch has conflicts so it's blocked by github.

2022-06-20 06:24 UTC, 4-1-1 commented
But their are relative , if set to trailing and keep empty line , will generate a not expect "\" in the last line

2022-06-20 06:44 UTC, 4-1-1 commented
But their are relative , if set to trailing and keep empty line , will generate a not expect \ in the last line 

> But they are relative , if set to trailing and keep empty line , will generate a not expect "" in the last line

I add a auto attr in paragraph to mark the trailing p

2022-06-20 06:58 UTC, Saul-Mirone commented
> 

This seems a bug related to https://github.com/Saul-Mirone/milkdown/issues/568, and I've been fixed it in latest main branch. Can you please reconfirm the behavior?

2022-06-20 08:38 UTC, 4-1-1 commented
It's not same , the problem is when i just look at a table, no editing  at all, but the value changed

<img width="990" alt="image" src="https://user-images.githubusercontent.com/4401981/174560911-c0fd4aae-1421-49eb-9633-c9d31f85c1c2.png">

2022-06-20 08:41 UTC, 4-1-1 commented
> I think your PR has two features:
> 
> 1. Keep empty lines in markdown
> 2. Add trailing node plugin
> 
> I don't plan to make feature 1 part of official plugins because I think it's not part of markdown standard and the implementation is a little bit tricky. It would be better to make it as a community plugin.
> 
> The feature 2 is a good feature but I think you should make it as a standalone plugin rather than part of commonmark preset.
> 
> BTW, the branch has conflicts so it's blocked by github.

If  to make it as a plugin agian. is it ok to keep this code in paragraph ? or any suggestion
```typescript 
                        if (!node.attrs['auto']) {
                            state.addNode('text', undefined, undefined, {
                                value: '\\',
                            });
                        }
```

2022-06-20 09:38 UTC, Saul-Mirone commented
> It's not same , the problem is when i just look at a table, no editing at all, but the value changed
> 
> <img alt="image" width="990" src="https://user-images.githubusercontent.com/4401981/174560911-c0fd4aae-1421-49eb-9633-c9d31f85c1c2.png">

I think you should check the node level in documentation, which means only add trailing node when you're in top level, similar to plugin-slash, it'll only show placeholder when the cursor at top level of the document

2022-06-20 10:52 UTC, 4-1-1 commented
> > It's not same , the problem is when i just look at a table, no editing at all, but the value changed
> > <img alt="image" width="990" src="https://user-images.githubusercontent.com/4401981/174560911-c0fd4aae-1421-49eb-9633-c9d31f85c1c2.png">
> 
> I think you should check the node level in documentation, which means only add trailing node when you're in top level, similar to plugin-slash, it'll only show placeholder when the cursor at top level of the document
> 
> https://github.com/Saul-Mirone/milkdown/blob/a6405ec1544763a362983d3a5bff6fabef5320f3/packages/plugin-slash/src/prose-plugin/props.ts#L77

Do you mean make a Decoration ? But  as i know It cannot  be focus  and selected

2022-06-20 11:12 UTC, 4-1-1 commented
is There a way to detect a node is a top level paragraph where runner toMarkdown?

2022-06-20 11:57 UTC, Saul-Mirone commented
No, I mean you should do the detection of top level when the editor view update.

2022-06-20 12:23 UTC, Saul-Mirone commented
I created a PR in https://github.com/Saul-Mirone/milkdown/pull/573 to show what I'm talking about.
I'll add you as the co-author of the PR.

2022-06-21 01:20 UTC, 4-1-1 commented
> I created a PR in #573 to show what I'm talking about. I'll add you as the co-author of the PR.

thanks

2022-06-22 06:54 UTC, Saul-Mirone commented
Closed for #573.

2022-06-22 06:54 UTC, closed without merging